"""
Analysis commands: analyze-jd, generate-candidate-profile, match-experiences.
"""
from pathlib import Path
from typing import Optional

import typer

from . import app


@app.command(name="analyze-jd")
def analyze_jd_cmd(
    jd: str = typer.Option(..., help="Path to JD markdown file"),
    app_folder: Optional[str] = typer.Option(None, "--app", help="Path to application folder"),
    lang: Optional[str] = typer.Option(None, "--lang", help="Output language: en or zh (overrides config)"),
):
    """Analyze a job description with LLM and output structured insights."""
    from ..jd_analyzer import analyze_jd
    from ..config import get_config

    jd_path = Path(jd)
    if not jd_path.exists():
        typer.echo(f"Error: JD file not found — {jd_path}")
        raise typer.Exit(1)

    jd_text = jd_path.read_text(encoding="utf-8")

    config = get_config()
    language = lang or config.language

    typer.echo("Analyzing JD...", err=True)
    try:
        result = analyze_jd(jd_text, language=language)
    except ValueError as e:
        typer.echo(f"Error: {e}")
        raise typer.Exit(1)

    def _bullets(items: list) -> str:
        return "\n".join(f"- {item}" for item in items)

    output = f"""# JD Analysis

## Role Type
{result.role_type} — {result.sub_role}

## Core Tasks
{_bullets(result.core_tasks)}

## Required Skills
{_bullets(result.required_skills)}

## Preferred Skills
{_bullets(result.preferred_skills)}

## Keywords
{", ".join(result.keywords)}

## Hidden Filters
{_bullets(result.hidden_filters)}

## Ideal Candidate
{result.ideal_candidate_summary}

## Resume Strategy
{result.resume_strategy}

## Interview Focus
{_bullets(result.interview_focus)}

## Red Flags
{_bullets(result.red_flags)}

---
Generated by ApplySmith | Model: {config.model}
"""

    if app_folder:
        dest = Path(app_folder) / "02_jd_analysis.md"
        dest.write_text(output, encoding="utf-8")
        # Write JSON sidecar so downstream commands can reload the structured data
        sidecar = Path(app_folder) / "02_jd_analysis.json"
        sidecar.write_text(result.model_dump_json(indent=2), encoding="utf-8")
        typer.echo(f"JD analysis written to: {dest}")
    else:
        typer.echo(output)


@app.command(name="generate-candidate-profile")
def generate_candidate_profile_cmd(
    app_folder: str = typer.Option(..., "--app", help="Path to application folder"),
    lang: Optional[str] = typer.Option(None, "--lang", help="Output language: en or zh (overrides config)"),
):
    """Generate ideal candidate profile from 02_jd_analysis.md."""
    import json
    from ..ideal_candidate import generate_ideal_candidate
    from ..models import JDAnalysis
    from ..config import get_config

    config = get_config()
    language = lang or config.language

    jd_analysis_path = Path(app_folder) / "02_jd_analysis.md"
    if not jd_analysis_path.exists():
        typer.echo(f"Error: 02_jd_analysis.md not found in {app_folder}")
        typer.echo("Run: applysmith analyze-jd first.")
        raise typer.Exit(1)

    # Re-derive JDAnalysis from the stored JSON sidecar if present,
    # otherwise ask user to re-run analyze-jd with --app to get the sidecar.
    sidecar = Path(app_folder) / "02_jd_analysis.json"
    if not sidecar.exists():
        typer.echo(f"Error: 02_jd_analysis.json not found in {app_folder}")
        typer.echo("Re-run: applysmith analyze-jd --jd <jd_file> --app <app_folder>")
        raise typer.Exit(1)

    jd_analysis = JDAnalysis(**json.loads(sidecar.read_text(encoding="utf-8")))

    typer.echo("Generating ideal candidate profile...", err=True)
    try:
        result = generate_ideal_candidate(jd_analysis, language=language)
    except ValueError as e:
        typer.echo(f"Error: {e}")
        raise typer.Exit(1)

    def _bullets(items: list) -> str:
        return "\n".join(f"- {item}" for item in items)

    output = f"""# Ideal Candidate Profile

## Role Type
{result.role_type}

## Background Summary
{result.background_summary}

## Must-Have Experiences
{_bullets(result.must_have_experiences)}

## Nice-to-Have Experiences
{_bullets(result.nice_to_have_experiences)}

## Must-Have Skills
{_bullets(result.must_have_skills)}

## Differentiators
{_bullets(result.differentiators)}

## Red-Line Filters
{_bullets(result.red_line_filters)}

---
Generated by ApplySmith | Model: {config.model}
"""

    dest = Path(app_folder) / "05_ideal_candidate.md"
    dest.write_text(output, encoding="utf-8")

    # Write JSON sidecar for downstream commands
    sidecar_out = Path(app_folder) / "05_ideal_candidate.json"
    sidecar_out.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    typer.echo("Ideal candidate profile generated.")
    typer.echo(f"  Written to: {dest}")


@app.command(name="match-experiences")
def match_experiences_cmd(
    app_folder: str = typer.Option(..., "--app", help="Path to application folder"),
    profile: str = typer.Option(..., "--profile", help="Path to experience_atoms.md"),
    lang: Optional[str] = typer.Option(None, "--lang", help="Output language: en or zh (overrides config)"),
):
    """Match experience atoms against the ideal candidate profile."""
    import json
    from ..experience_matcher import match_experiences
    from ..models import IdealCandidate
    from ..config import get_config

    config = get_config()
    language = lang or config.language

    sidecar = Path(app_folder) / "05_ideal_candidate.json"
    if not sidecar.exists():
        typer.echo(f"Error: 05_ideal_candidate.json not found in {app_folder}")
        typer.echo("Run: applysmith generate-candidate-profile first.")
        raise typer.Exit(1)

    profile_path = Path(profile)
    if not profile_path.exists():
        typer.echo(f"Error: experience_atoms.md not found — {profile_path}")
        raise typer.Exit(1)

    from ..metric_extractor import extract_metrics

    ideal = IdealCandidate(**json.loads(sidecar.read_text(encoding="utf-8")))
    atoms_text = profile_path.read_text(encoding="utf-8")

    typer.echo("Matching experiences...", err=True)
    try:
        result = match_experiences(ideal, atoms_text, language=language)
    except ValueError as e:
        typer.echo(f"Error: {e}")
        raise typer.Exit(1)

    def _bullets(items: list) -> str:
        return "\n".join(f"- {item}" for item in items)

    included_sections = []
    for exp in result.included:
        included_sections.append(
            f"### {exp.experience_name} — {exp.match_level}\n"
            f"**Why matched:** {exp.why_matched}\n"
            f"**Suggested angle:** {exp.suggested_angle}\n"
            f"**Risk notes:** {exp.risk_notes}"
        )

    excluded_sections = []
    for exp in result.excluded:
        excluded_sections.append(
            f"### {exp.experience_name} — Irrelevant\n"
            f"**Why excluded:** {exp.why_matched}"
        )

    output = f"""# Selected Experiences

## Included Experiences

{chr(10).join(included_sections) if included_sections else "_None_"}

## Excluded Experiences

{chr(10).join(excluded_sections) if excluded_sections else "_None_"}

## Packaging Strategy
{result.packaging_notes}

## Capability Gaps
{_bullets(result.capability_gaps) if result.capability_gaps else "_None identified_"}

---
Generated by ApplySmith | Model: {config.model}
"""

    dest = Path(app_folder) / "06_selected_experiences.md"
    dest.write_text(output, encoding="utf-8")
    sidecar_out = Path(app_folder) / "06_selected_experiences.json"
    sidecar_out.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    # Save metric whitelist for use by generate-resume
    metric_whitelist = extract_metrics(atoms_text)
    whitelist_path = Path(app_folder) / "metrics_whitelist.json"
    whitelist_path.write_text(json.dumps(metric_whitelist, ensure_ascii=False, indent=2), encoding="utf-8")

    n_included = len(result.included)
    n_gaps = len(result.capability_gaps)
    typer.echo(f"{n_included} experiences matched, {n_gaps} gaps identified.")
    typer.echo(f"  Written to: {dest}")
