"""
Generation commands: generate-resume, check-claims, generate-defense, build-gap-plan.
"""
import json
from pathlib import Path
from typing import Optional

import typer

from . import app


@app.command(name="generate-resume")
def generate_resume_cmd(
    app_folder: str = typer.Option(..., "--app", help="Path to application folder"),
    company: str = typer.Option(..., "--company", help="Target company name"),
    role: str = typer.Option(..., "--role", help="Target role name"),
    lang: Optional[str] = typer.Option(None, "--lang", help="Output language: en or zh (overrides config)"),
    profile: Optional[str] = typer.Option(
        None, "--profile",
        help="Path to experience_atoms.md for verbatim metric-source verification",
    ),
):
    """Generate tailored resume bullets from selected experiences."""
    from ..resume_generator import generate_resume
    from ..models import ExperienceSelectionResult, IdealCandidate
    from ..config import get_config

    config = get_config()
    language = lang or config.language

    sel_sidecar = Path(app_folder) / "06_selected_experiences.json"
    ideal_sidecar = Path(app_folder) / "05_ideal_candidate.json"

    for p, label in [(sel_sidecar, "06_selected_experiences.json"), (ideal_sidecar, "05_ideal_candidate.json")]:
        if not p.exists():
            typer.echo(f"Error: {label} not found in {app_folder}")
            raise typer.Exit(1)

    selection = ExperienceSelectionResult(**json.loads(sel_sidecar.read_text(encoding="utf-8")))
    ideal = IdealCandidate(**json.loads(ideal_sidecar.read_text(encoding="utf-8")))

    # Load metric whitelist if available (written by match-experiences)
    whitelist_path = Path(app_folder) / "metrics_whitelist.json"
    metric_whitelist = (
        json.loads(whitelist_path.read_text(encoding="utf-8"))
        if whitelist_path.exists() else None
    )

    # Load experience atoms for verbatim metric-source verification.
    # Prefer explicit --profile flag; fall back to cached snapshot in app folder.
    atoms_raw: Optional[str] = None
    snapshot_path = Path(app_folder) / "experience_atoms_snapshot.md"
    if profile:
        atoms_path = Path(profile)
        if not atoms_path.exists():
            typer.echo(f"Error: experience_atoms.md not found — {atoms_path}")
            raise typer.Exit(1)
        atoms_raw = atoms_path.read_text(encoding="utf-8")
        # Cache a snapshot so check-claims can reuse it without --profile
        snapshot_path.write_text(atoms_raw, encoding="utf-8")
    elif snapshot_path.exists():
        atoms_raw = snapshot_path.read_text(encoding="utf-8")

    typer.echo("Generating resume...", err=True)
    try:
        result = generate_resume(
            selection, ideal, role, company,
            language=language,
            metric_whitelist=metric_whitelist,
            atoms_raw=atoms_raw,
        )
    except ValueError as e:
        typer.echo(f"Error: {e}")
        raise typer.Exit(1)

    def _bullet_section(b) -> str:
        source_line = (
            f"**Metric source:** {b.metric_source}\n" if b.metric_source else ""
        )
        return (
            f"### {b.experience_name}\n"
            f"{b.bullet_text}\n"
            f"{source_line}"
            f"**Evidence:** {b.evidence}\n"
            f"**Interview risk:** {b.interview_risk}\n"
            f"**Action required:** {b.recommended_action}\n"
            f"**Claim level:** {b.claim_level}"
        )

    bullets_md = "\n\n".join(_bullet_section(b) for b in result.bullets)

    output = f"""# Tailored Resume

## Target Role
{result.target_role} at {result.target_company}

## Summary
{result.summary_statement}

## Experience Bullets

{bullets_md}

## Packaging Notes
{result.packaging_notes}

---
Generated by ApplySmith | Model: {config.model}
"""

    dest = Path(app_folder) / "07_tailored_resume.md"
    dest.write_text(output, encoding="utf-8")
    sidecar_out = Path(app_folder) / "07_tailored_resume.json"
    sidecar_out.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    typer.echo(f"Resume generated: {len(result.bullets)} bullets")
    typer.echo(f"  Written to: {dest}")


@app.command(name="check-claims")
def check_claims_cmd(
    app_folder: str = typer.Option(..., "--app", help="Path to application folder"),
    lang: Optional[str] = typer.Option(None, "--lang", help="Output language: en or zh (overrides config)"),
):
    """Run an independent claim audit on the tailored resume."""
    from ..claim_checker import check_claims
    from ..models import TailoredResume
    from ..config import get_config

    config = get_config()
    language = lang or config.language

    sidecar = Path(app_folder) / "07_tailored_resume.json"
    if not sidecar.exists():
        typer.echo(f"Error: 07_tailored_resume.json not found in {app_folder}")
        typer.echo("Run: applysmith generate-resume first.")
        raise typer.Exit(1)

    resume = TailoredResume(**json.loads(sidecar.read_text(encoding="utf-8")))

    # Reuse the atoms snapshot saved by generate-resume for verbatim source checks
    atoms_raw: Optional[str] = None
    snapshot_path = Path(app_folder) / "experience_atoms_snapshot.md"
    if snapshot_path.exists():
        atoms_raw = snapshot_path.read_text(encoding="utf-8")

    typer.echo("Checking claims...", err=True)
    try:
        result = check_claims(resume, language=language, atoms_raw=atoms_raw)
    except ValueError as e:
        typer.echo(f"Error: {e}")
        raise typer.Exit(1)

    from collections import Counter
    counts = Counter(b.claim_level for b in result.bullets)

    def _section(level: str, icon: str, show_risk: bool) -> str:
        items = [b for b in result.bullets if b.claim_level == level]
        if not items:
            return ""
        lines = [f"## {level} Claims {icon}"]
        for b in items:
            lines.append(f"### {b.bullet_text}")
            lines.append(f"Evidence: {b.evidence}")
            if show_risk and b.interview_risk:
                lines.append(f"Risk: {b.interview_risk}")
            if b.recommended_action:
                lines.append(f"Action: {b.recommended_action}")
        return "\n".join(lines)

    sections = "\n\n".join(filter(None, [
        _section("Green", "✅", show_risk=False),
        _section("Yellow", "⚠️", show_risk=True),
        _section("Red", "❌", show_risk=True),
        _section("Buildable", "🔨", show_risk=False),
        _section("Stretch", "🎯", show_risk=True),
    ]))

    output = f"""# Claim Check Report

## Overall Risk: {result.overall_risk}
{result.summary}

{sections}

---
Generated by ApplySmith | Model: {config.model}
"""

    dest = Path(app_folder) / "08_claim_check_report.md"
    dest.write_text(output, encoding="utf-8")
    sidecar_out = Path(app_folder) / "08_claim_check_report.json"
    sidecar_out.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    summary_line = " | ".join(
        f"{lvl}: {counts.get(lvl, 0)}"
        for lvl in ["Green", "Yellow", "Red", "Buildable", "Stretch"]
    )
    typer.echo(summary_line)
    typer.echo(f"Overall risk: {result.overall_risk}")
    typer.echo(f"  Written to: {dest}")


@app.command(name="generate-defense")
def generate_defense_cmd(
    app_folder: str = typer.Option(..., "--app", help="Path to application folder"),
    lang: Optional[str] = typer.Option(None, "--lang", help="Output language: en or zh (overrides config)"),
):
    """Generate interview defense guide from tailored resume and claim check report."""
    from ..interview_defense import generate_defense
    from ..models import TailoredResume, ClaimCheckReport
    from ..config import get_config

    config = get_config()
    language = lang or config.language

    resume_sidecar = Path(app_folder) / "07_tailored_resume.json"
    claim_sidecar = Path(app_folder) / "08_claim_check_report.json"

    for p, label in [
        (resume_sidecar, "07_tailored_resume.json"),
        (claim_sidecar, "08_claim_check_report.json"),
    ]:
        if not p.exists():
            typer.echo(f"Error: {label} not found in {app_folder}")
            raise typer.Exit(1)

    resume = TailoredResume(**json.loads(resume_sidecar.read_text(encoding="utf-8")))
    claim_report = ClaimCheckReport(**json.loads(claim_sidecar.read_text(encoding="utf-8")))

    typer.echo("Generating interview defense...", err=True)
    try:
        result = generate_defense(resume, claim_report, language=language)
    except ValueError as e:
        typer.echo(f"Error: {e}")
        raise typer.Exit(1)

    def _bullets(items: list) -> str:
        return "\n".join(f"- {item}" for item in items)

    def _numbered(items: list) -> str:
        return "\n".join(f"{i+1}. {item}" for i, item in enumerate(items))

    defense_sections = []
    for n, bd in enumerate(result.bullet_defenses, 1):
        defense_sections.append(
            f"### Bullet {n}: {bd.bullet_text}\n"
            f"**Claim Level:** {bd.claim_level}\n\n"
            f"**Likely Questions:**\n{_numbered(bd.likely_questions)}\n\n"
            f"**Answer Framework:**\n{bd.answer_framework}\n\n"
            f"**Key Talking Points:**\n{_bullets(bd.key_talking_points)}\n\n"
            f"**Risk Boundary:**\n{bd.risk_boundary}\n\n"
            f"**Evidence to Prepare:**\n{_bullets(bd.evidence_to_prepare)}\n\n"
            f"**Do NOT Say:**\n{_bullets(bd.what_not_to_say)}"
        )

    output = f"""# Interview Defense Guide

## Target Role
{result.target_role} at {result.target_company}

## Overall Strategy
{result.overall_strategy}

---

## Bullet-by-Bullet Defense

{chr(10).join(f"{s}{chr(10)}{chr(10)}---" for s in defense_sections)}

## General Interview Questions
{_numbered(result.general_questions)}

## Capability Gap Questions
> These questions target known gaps.
> Prepare honest, forward-looking answers.
{_numbered(result.capability_gap_questions)}

---
Generated by ApplySmith | Model: {config.model}
"""

    dest = Path(app_folder) / "09_interview_defense.md"
    dest.write_text(output, encoding="utf-8")
    sidecar_out = Path(app_folder) / "09_interview_defense.json"
    sidecar_out.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    n_bullets = len(result.bullet_defenses)
    n_gaps = len(result.capability_gap_questions)
    typer.echo(f"{n_bullets} bullets defended | {n_gaps} gap questions identified")
    typer.echo(f"  Written to: {dest}")


@app.command(name="build-gap-plan")
def build_gap_plan_cmd(
    app_folder: str = typer.Option(..., "--app", help="Path to application folder"),
    lang: Optional[str] = typer.Option(None, "--lang", help="Output language: en or zh (overrides config)"),
):
    """Generate a capability gap learning and simulation plan."""
    from ..gap_builder import build_gap_plan
    from ..models import ExperienceSelectionResult
    from ..config import get_config

    config = get_config()
    language = lang or config.language

    sel_sidecar = Path(app_folder) / "06_selected_experiences.json"
    if not sel_sidecar.exists():
        typer.echo(f"Error: 06_selected_experiences.json not found in {app_folder}")
        typer.echo("Run: applysmith match-experiences first.")
        raise typer.Exit(1)

    selection = ExperienceSelectionResult(**json.loads(sel_sidecar.read_text(encoding="utf-8")))

    if not selection.capability_gaps:
        typer.echo("No capability gaps found. Nothing to plan.")
        raise typer.Exit(0)

    # Read target info from resume sidecar if available
    resume_sidecar = Path(app_folder) / "07_tailored_resume.json"
    if resume_sidecar.exists():
        resume_data = json.loads(resume_sidecar.read_text(encoding="utf-8"))
        target_role = resume_data.get("target_role", "unknown role")
        target_company = resume_data.get("target_company", "unknown company")
    else:
        target_role = "target role"
        target_company = "target company"

    typer.echo("Building capability gap plan...", err=True)
    try:
        result = build_gap_plan(selection.capability_gaps, target_role, target_company, language=language)
    except ValueError as e:
        typer.echo(f"Error: {e}")
        raise typer.Exit(1)

    def _bullets(items: list) -> str:
        return "\n".join(f"- {item}" for item in items)

    def _numbered(items: list) -> str:
        return "\n".join(f"{i+1}. {item}" for i, item in enumerate(items))

    learning_sections = []
    for lt in result.learning_tasks:
        learning_sections.append(
            f"### {lt.skill} — Priority: {lt.priority}\n"
            f"**Why needed:** {lt.why_needed}\n"
            f"**Estimated time:** {lt.estimated_hours}\n"
            f"**Resources:**\n{_bullets(lt.learning_resources)}"
        )

    project_sections = []
    for sp in result.simulation_projects:
        project_sections.append(
            f"### Project: {sp.project_title}\n"
            f"**Skill:** {sp.skill}\n"
            f"**Project type:** {sp.project_type}\n\n"
            f"> ⚠️ {sp.warning}\n\n"
            f"**Datasets to use:**\n{_bullets(sp.dataset_suggestions)}\n\n"
            f"**Deliverables:**\n{_bullets(sp.deliverables)}\n\n"
            f"**Resume bullet template:**\n{sp.resume_bullet_template}\n\n"
            f"**How to defend in interview:**\n{sp.interview_defense_notes}"
        )

    output = f"""# Capability Gap Plan

## Target Role
{result.target_role} at {result.target_company}

## Identified Gaps
{_bullets(result.gaps)}

## Priority Order
{_numbered(result.priority_order)}

## Weekly Action Plan
{result.weekly_action_plan}

---

## Learning Tasks

{chr(10).join(f"{s}{chr(10)}{chr(10)}---" for s in learning_sections)}

## Simulation Projects

{chr(10).join(f"{s}{chr(10)}{chr(10)}---" for s in project_sections)}

Generated by ApplySmith | Model: {config.model}
"""

    dest = Path(app_folder) / "gap_plan.md"
    dest.write_text(output, encoding="utf-8")
    sidecar_out = Path(app_folder) / "gap_plan.json"
    sidecar_out.write_text(result.model_dump_json(indent=2), encoding="utf-8")

    typer.echo(
        f"{len(result.gaps)} gaps identified | "
        f"{len(result.learning_tasks)} learning tasks | "
        f"{len(result.simulation_projects)} projects suggested"
    )
    typer.echo(f"  Written to: {dest}")
