"""
Tests for LLM client, JD analyzer, and analyze-jd CLI command.
No real API calls are made — call_llm is always mocked.
"""
import json
import os
from pathlib import Path
from unittest.mock import patch

import pytest
from typer.testing import CliRunner

from applysmith.cli import app
from applysmith.jd_analyzer import analyze_jd
from applysmith.models import JDAnalysis


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

MOCK_ANALYSIS = {
    "role_type": "Product",
    "sub_role": "Growth Product Manager",
    "core_tasks": ["Define growth metrics", "Run A/B tests"],
    "required_skills": ["SQL", "Product sense"],
    "preferred_skills": ["Python", "Mixpanel"],
    "keywords": ["growth", "retention", "funnel"],
    "hidden_filters": ["Startup experience preferred"],
    "ideal_candidate_summary": "Data-driven PM with 3+ years growth experience.",
    "resume_strategy": "Lead with quantified growth wins.",
    "interview_focus": ["Metric selection", "Experiment design"],
    "red_flags": ["Vague success criteria"],
}

MOCK_JSON = json.dumps(MOCK_ANALYSIS)

runner = CliRunner()


# ---------------------------------------------------------------------------
# 1. test_llm_client_no_key
# ---------------------------------------------------------------------------

def test_llm_client_no_key():
    """call_llm raises a clear ValueError when APPLYSMITH_API_KEY is not set."""
    from applysmith.config import Config
    from applysmith.llm_client import call_llm

    no_key_config = Config(model="deepseek/deepseek-chat", api_key=None, api_base=None, language="en")
    with patch("applysmith.llm_client.get_config", return_value=no_key_config):
        with pytest.raises(ValueError, match="APPLYSMITH_API_KEY"):
            call_llm("sys", "user")


# ---------------------------------------------------------------------------
# 2. test_jd_analyzer_mock
# ---------------------------------------------------------------------------

def test_jd_analyzer_mock():
    """JDAnalysis is correctly parsed from mocked LLM JSON response."""
    with patch("applysmith.llm_client.call_llm", return_value=MOCK_JSON):
        result = analyze_jd("Some JD text")

    assert isinstance(result, JDAnalysis)
    assert result.role_type == "Product"
    assert result.sub_role == "Growth Product Manager"
    assert "SQL" in result.required_skills
    assert len(result.core_tasks) == 2


# ---------------------------------------------------------------------------
# 3. test_analyze_jd_command_no_app
# ---------------------------------------------------------------------------

def test_analyze_jd_command_no_app(tmp_path):
    """analyze-jd prints markdown to terminal when --app is not provided."""
    jd_file = tmp_path / "jd.md"
    jd_file.write_text("Sample JD content", encoding="utf-8")

    with patch("applysmith.llm_client.call_llm", return_value=MOCK_JSON):
        result = runner.invoke(app, ["analyze-jd", "--jd", str(jd_file)])

    assert result.exit_code == 0
    assert "## Role Type" in result.output
    assert "Growth Product Manager" in result.output
    assert "Generated by ApplySmith" in result.output


# ---------------------------------------------------------------------------
# 4. test_analyze_jd_command_with_app
# ---------------------------------------------------------------------------

def test_analyze_jd_command_with_app(tmp_path):
    """analyze-jd writes 02_jd_analysis.md when --app is provided."""
    jd_file = tmp_path / "jd.md"
    jd_file.write_text("Sample JD content", encoding="utf-8")

    app_folder = tmp_path / "my_application"
    app_folder.mkdir()

    with patch("applysmith.llm_client.call_llm", return_value=MOCK_JSON):
        result = runner.invoke(
            app,
            ["analyze-jd", "--jd", str(jd_file), "--app", str(app_folder)],
        )

    assert result.exit_code == 0
    out_file = app_folder / "02_jd_analysis.md"
    assert out_file.exists(), "02_jd_analysis.md was not created"
    content = out_file.read_text(encoding="utf-8")
    assert "## Role Type" in content
    assert "Growth Product Manager" in content
    assert "Generated by ApplySmith" in content
